config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :restaurants, only: :show do
    # resources :reviews, only: [:create]
    resources :saved_restaurants, only: [:create]
    # resources :collections, only: [:new, :create, :index]
    resources :collections, only: [:index]
  end

  resources :saved_restaurants, only: [:update] do
    resources :reviews, only: [:create]
  end
  resources :reviews, only: [:destroy]

  resources :restaurants do
    patch "update_collection", to: "restaurants#update_collection", as: :collection
  end

  # get "/restaurants/:id", to: "restaurants#show", as: "restaurant"

  # À VÉRIFIER
  resources :collections, only: [:new, :create, :index, :show, :destroy]

  resources :friendships, except: %i[edit update new]
  get "friendships", to: "friendship#new"

  patch "friendships/:id/accept", to: "friendships#accept", as: :accept
  patch "friendships/:id/decline", to: "friendships#decline", as: :decline

  get "dashboard", to: "pages#dashboard"
  post 'dashboard/switch-window/:tab_name', to: "pages#switch_window", as: :switch_tab
  get "feed", to: "pages#feed"
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user

  has_many :saved_restaurants_collections
  has_many :saved_restaurants, through: :saved_restaurants_collections
  has_many :restaurants, through: :saved_restaurants

  validates :name, presence: true, uniqueness: { scope: :user_id, message: "You already have a collection with this name" }
  validates :color, presence: true
  validates :emoji, presence: true
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def index
    @friends_restaurants = current_user.friends_restaurants
    @collections = current_user.collections
    collection_name = params[:name]

    if collection_name
      @restaurants = Collection.find_by(user: current_user, name: collection_name).restaurants
    elsif params[:friends]
      @restaurants = @friends_restaurants
    else
      @restaurants = current_user.restaurants.distinct
    end

    @markers = @restaurants.geocoded.map do |restaurant|
      # si on filtre nos restaurants par collection
      if collection_name
        # collection = restaurant.saved_restaurants.find_by(user: current_user).collections.first
        collection = @collections.find_by(name: collection_name)
      # si on filtre en affichant les restaurants de nos friends
      elsif params[:friends]
        # friends_ids = current_user.friends.pluck(:id)
        friends = current_user.friends
        collection = SavedRestaurant.where(user: friends, restaurant: restaurant).first.collections.first
      # si on affiche tous nos restaurants
      else
        collection = restaurant.saved_restaurants.find_by(user: current_user).collections.first
      end

      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { restaurant: restaurant, collection: collection }),
        marker_html: render_to_string(partial: "marker", locals: { restaurant: restaurant, collection: collection })
      }
    end

    respond_to do |format|
      format.html
      format.turbo_stream if params[:name] || params[:friends]
    end
  end

  def show
    @collection = Collection.find(params[:id])
  end

  def new
    @collection = Collection.new
  end

  def create
    @user = current_user
    @collection = Collection.new(collection_params)
    @collection.user_id = @user.id
    if @collection.save
      redirect_to dashboard_path
    else
      set_collections
      @show_modal = true
      render 'pages/dashboard', status: :unprocessable_entity
    end
  end

  def destroy
    @collection = Collection.find(params[:id])
    @collection.destroy
    redirect_to collection_path()
  end

  private

  def collection_params
    params.require(:collection).permit(:name, :color, :emoji)
  end

  def set_collections
    @collections = @user.collections
  end
end

app/views/collections/_card.html.erb
<div class="card-vignette rounded-5 mx-auto border border-1 my-3">
  <p><%= link_to restaurant.name, restaurant_path(restaurant),  class: "text-deco-none" %></p>
  <p><%= restaurant.rating %> </p>
  <p><%= restaurant.address %> </p>
</div>

app/views/collections/_info_window.html.erb
<%= render 'components/map_restaurant_card', restaurant: restaurant, collection: collection %>

app/views/collections/_marker.html.erb
<div style="width: 40px; height: 40px; background-color: <%= collection.color %>;" class="fs-1 text-center d-flex justify-content-center align-items-center rounded-circle">
  <% if collection.user === current_user %>
    <%= collection.emoji %>
  <% else %>
    <% if collection.user.avatar_color.present? %>
      <div class="user-avatar" style="width: 40px; height: 40px; background-color: <%= collection.user.avatar_color %>;">
        <%= collection.user.first_name[0] %><%= collection.user.last_name[0] %>
      </div>
    <% else %>
      <%= image_tag "https://png.pngtree.com/png-vector/20221018/ourmid/pngtree-master-chef-logo-illustration-png-image_6351381.png", class: "friend-card-avatar" %>
    <% end %>
  <% end %>
</div>

app/views/collections/index.html.erb
<div class="main-content">
  <div data-controller="showcat" class="relative">

    <div id="mapbox-collection" style="box-shadow: 0 4px 7px rgba(0, 0, 0, 0.3);"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      <div class="row">
        <div class="col-12 d-flex justify-content-between mx-auto my-3" style="width: 85%; z-index: 4;">
          <%= link_to "All", collections_path(),
          data: { action: "click->showcat#toggle", showcat_target: "allLink", turbo_stream: true },
          class: "btn-link no-padding d-flex align-items-center justify-content-center" %>
          <button data-action="click->showcat#toggle" data-showcat-target="colLink" class="btn-no-link no-padding d-flex align-items-center justify-content-center">Collections</button>
          <%= link_to "Friends", collections_path(friends: true), data: { action:"click->showcat#toggle", showcat_target:"friendLink", turbo_stream: true }, class: "btn-no-link no-padding d-flex align-items-center justify-content-center" %>
        </div>
      </div>
    </div>
    <div id="info-bulle" class="d-none" style="width: 90vw; position: fixed; bottom: 100px; left: 50%; transform: translateX(-50%); padding: 10px; border-radius: 5px;"></div>

    <div id="collection-filters" class="d-none absolute bg-white mx-auto d-flex flex-column align-items-center my-2 rounded-5" style="width: 60%; box-shadow: 0 4px 7px rgba(0, 0, 0, 0.3);" data-showcat-target="collections">
      <% @collections.each_with_index do |collection, index| %>
        <% if (collection.saved_restaurants.present?)%>
          <%= link_to collection.name, collections_path(name: collection.name, color: collection.color, emoji: collection.emoji), data: { turbo_stream: true }, class: "btn-collection no-padding d-flex align-items-center justify-content-center my-2 rounded-5" %>
          <div class="d-none">
            <% collection.saved_restaurants.each do |saved_restaurant| %>
              <p><%= link_to saved_restaurant.restaurant.name, restaurant_path(saved_restaurant.restaurant) %></p>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/collections/index.turbo_stream.erb
<%= turbo_stream.set_dataset_attribute("#mapbox-collection", "map-markers-value", @markers.to_json) %>
<%= turbo_stream.add_css_class("#collection-filters", "d-none") %>
<%= turbo_stream.add_css_class("#info-bulle", "d-none") %>

app/views/collections/new.html.erb
<h1>Create new collection</h1>
<%= simple_form_for(@collection) do |f| %>
  <%= f.input :name, label: 'Name' %>
  <div class="colors-iteration mb-4">
    <% COLORS.each_with_index do |color, index| %>
      <input type="radio" id="color_<%= index %>" name="collection[color]" value="<%= color %>" class="input-none">
      <label for="color_<%= index %>" style="background-color:<%= color %>;" class="color-button"></label>
    <% end %>
  </div>
  <div class="emojis-iteration mb-4">
    <% EMOJIS.each_with_index do |emoji, index| %>
      <input type="radio" id="emoji_<%= index %>" name="collection[emoji]" value="<%= emoji %>" class="input-none">
      <label for="emoji_<%= index %>" class="emoji-button"><%= emoji %></label>
    <% end %>
  </div>
  <%= f.submit 'Create' %>
<% end %>

app/views/collections/show.html.erb
<h1><%= @collection.name %></h1>