config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :restaurants, only: :show do
    # resources :reviews, only: [:create]
    resources :saved_restaurants, only: [:create]
    # resources :collections, only: [:new, :create, :index]
    resources :collections, only: [:index]
  end

  resources :saved_restaurants, only: [:update] do
    resources :reviews, only: [:create]
  end
  resources :reviews, only: [:destroy]

  resources :restaurants do
    patch "update_collection", to: "restaurants#update_collection", as: :collection
  end

  # get "/restaurants/:id", to: "restaurants#show", as: "restaurant"

  # À VÉRIFIER
  resources :collections, only: [:new, :create, :index, :show, :destroy]

  resources :friendships, except: %i[edit update new]
  get "friendships", to: "friendship#new"

  patch "friendships/:id/accept", to: "friendships#accept", as: :accept
  patch "friendships/:id/decline", to: "friendships#decline", as: :decline

  get "dashboard", to: "pages#dashboard"
  post 'dashboard/switch-window/:tab_name', to: "pages#switch_window", as: :switch_tab
  get "feed", to: "pages#feed"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
    <%= link_to root_path, class: "nav-item #{'active' if current_page?(root_path)}" do %>
      <% if current_page?(root_path) %>
        <%= image_tag "home-active.svg" %>
      <% else %>
        <%= image_tag "home.svg" %>
      <% end %>
      <span>HOME</span>
    <% end %>

    <%= link_to  collections_path, class: "nav-item #{'active' if current_page?(collections_path)}" do %>
      <% if current_page?(collections_path) %>
        <%= image_tag "maps-active.svg" %>
      <% else %>
        <%= image_tag "maps.svg" %>
      <% end %>
      <span>MAPS</span>
    <% end %>

    <%= link_to feed_path, class: "nav-item #{'active' if current_page?(feed_path)}" do %>
      <% if current_page?(feed_path) %>
        <%= image_tag "feed-active.svg" %>
      <% else %>
        <%= image_tag "feed.svg" %>
      <% end %>
      <span>FEED</span>
    <% end %>

    <%= link_to friendships_path, class: "nav-item #{'active' if current_page?(friendships_path)}" do %>
      <% if current_page?(friendships_path) %>
        <%= image_tag "friends-active.svg" %>
      <% else %>
        <%= image_tag "friends.svg" %>
      <% end %>
      <span>FRIENDS</span>
    <% end %>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar-container">
  <div class="navbar">

    <!-- Section centrale avec logo -->
    <div class="navbar-brand">
      <%= image_tag "logoGusto.svg", alt: "Logo Gusto" %>
    </div>

    <!-- Si l'utilisateur est connecté -->
    <% if user_signed_in? %>
        <!-- Lien vers le dashboard avec l'avatar de l'utilisateur -->
        <%= link_to "/dashboard/", class: "navbar-profil" do %>
          <div class="user-avatar" style="background-color: <%= current_user.avatar_color %>;">
            <%= current_user.first_name[0] %><%= current_user.last_name[0] %>
          </div>
          <%#= cl_image_tag current_user.avatar.key, class: "avatar", alt: "avatar" %>
        <% end %>
      <!-- Si l'utilisateur n'est pas connecté -->
      <%# else %>
        <%#= link_to "/dashboard/", class: "navbar-profil" do %>
          <%#= image_tag "https://png.pngtree.com/png-vector/20221018/ourmid/pngtree-master-chef-logo-illustration-png-image_6351381.png", class: "avatar", alt: "avatar" %>
        <% end %>
      <%# end %>
    <%# end %>

    <!-- >
    <div class="d-flex justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Disconnect", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
    -->

  </div>
</div>