config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :restaurants, only: :show do
    # resources :reviews, only: [:create]
    resources :saved_restaurants, only: [:create]
    # resources :collections, only: [:new, :create, :index]
    resources :collections, only: [:index]
  end

  resources :saved_restaurants, only: [:update] do
    resources :reviews, only: [:create]
  end
  resources :reviews, only: [:destroy]

  resources :restaurants do
    patch "update_collection", to: "restaurants#update_collection", as: :collection
  end

  # get "/restaurants/:id", to: "restaurants#show", as: "restaurant"

  # À VÉRIFIER
  resources :collections, only: [:new, :create, :index, :show, :destroy]

  resources :friendships, except: %i[edit update new]
  get "friendships", to: "friendship#new"

  patch "friendships/:id/accept", to: "friendships#accept", as: :accept
  patch "friendships/:id/decline", to: "friendships#decline", as: :decline

  get "dashboard", to: "pages#dashboard"
  post 'dashboard/switch-window/:tab_name', to: "pages#switch_window", as: :switch_tab
  get "feed", to: "pages#feed"
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id', required: true
  enum status: { pending: 0, accepted: 1, decline: 2 }
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :destroy, :accept, :decline]

  def index
    @friendships = Friendship.all
    @users = User.all
    @users = @users.where("username ILIKE ?", "%#{params[:query]}%") if params[:query].present?
    @pending_friendships = @friendships.select { |f| f.status == "pending" }
    @accepted_friendships = @friendships.select { |f| f.status == "accepted" }
  end

  def show
     # J'assigne à ma variable d'instance "@user" le "current_user"
     @user = User.find(@friendship.user_id)
     # Récupération de tout les saved_restaurants de mon @user
     @saved_restaurants = @user.saved_restaurants
     # Récupération des collections de mon @user
     @collections = @user.collections
     @collection = @user.collections.where(name: "Favoris").first
  end

  def new
    @friendship = Friendship.new
  end

  def create
    @friendship = Friendship.new
    @friendship.user_id = current_user.id
    @friendship.friend_id = User.find(params[:format].to_i).id
    @friendship.save
    @friendship.pending!
    redirect_to friendships_path()
  end

  def destroy
    @friendship.destroy
    redirect_to friendships_path()
  end

  def accept
    @friendship.accepted!
    redirect_to friendships_path()
  end

  def decline
    @friendship.decline!
    @friendship.destroy
    redirect_to friendships_path()
  end

  private

  def set_friendship
    @friendship = Friendship.find(params[:id])
  end
end

app/views/friendships/index.html.erb
<!-- Idéalement code à mettre dans Friendships Controller -->
<% User.all.each do |user| %>
  <% friends = [] %>
  <% @friendships.each do |friendship| %>
    <% if (current_user == User.find(friendship.user_id)) %>
      <% friends.insert(-1, friendship.friend_id) %>
    <% end %>
  <% end %>
  <% unless (user == current_user || friends.include?(user.id)) %>
  <% end %>
<% end %>

<div class="main-content">

  <!-- Barre de recherche -->
  <div data-controller="reset">
    <%# J'affiche ma partial search-bar %>
    <%= render "components/searchbar_friend" %>
    <%# Je gère l'affichage des résultats %>
    <%# Si la valeur "query" dans params est présente %>
    <% if params[:query].present? %>
      <%# Je créé une div qui affichera mes résultats %>
      <div data-reset-target="list">
        <%# Si je trouve des restaurants dans les résultats de ma recherche %>
        <% @users.each do |user| %>
          <% friends = [] %>
          <% @friendships.each do |friendship| %>
            <% if (current_user == User.find(friendship.user_id)) %>
              <% friends.insert(-1, friendship.friend_id) %>
            <% end %>
          <% end %>
          <% unless (user == current_user || friends.include?(user.id)) %>
            <% if friends.any? %>
                <%= user.username %>
                <%= link_to "Add", friendships_path(user), data: {turbo_method: :post, turbo_confirm: "Are you sure?"}, class: "btn btn-success" %>
            <%# Sinon %>
            <% else %>
              <%# On affiche le message suivant %>
              <p>Sorry, no friends found.</p>
            <% end %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>

  <!-- Demande d'amis -->
  <div class="title-container">
    <h2>Friends Requests</h2>
  </div>

  <div class="friend-cards">
    <% @pending_friendships.each do |friendship| %>
      <%= render "components/friend_card", friendship: friendship %>
    <% end %>
  </div>

  <!-- Liste d'amis -->
  <div class="title-container">
    <h2>All Friends</h2>
    <p><%= Friendship.where(status: 1).where(user: current_user).or(Friendship.where(status: 1).where(friend: current_user)).count %> friends</p>
  </div>

  <div class="friend-cards">
    <% @accepted_friendships.each do |friendship| %>
      <%= render "components/friend_card", friendship: friendship %>
    <% end %>
  </div>

</div>

<!-- Barre de recherche -->

<!--
<div class="container m-3">
  <h1>Add a friend</h1>
  <% User.all.each do |user| %>
    <% friends = [] %>
    <% @friendships.each do |friendship| %>
      <% if (current_user == User.find(friendship.user_id)) %>
        <% friends.insert(-1, friendship.friend_id) %>
      <% end %>
    <% end %>
    <% unless (user == current_user || friends.include?(user.id)) %>
      <%# user.username %>
      <%# link_to "Add", friendships_path(user), data: {turbo_method: :post, turbo_confirm: "Are you sure?"}, class: "btn btn-success" %>
    <% end %>
  <% end %>
</div>

<div class="m-3" data-controller="reset">
  <%# J'affiche ma partial search-bar %>
  <%= render "components/searchbar_friend" %>
  <%# Je gère l'affichage des résultats %>
  <%# Si la valeur "query" dans params est présente %>
  <% if params[:query].present? %>
    <%# Je créé une div qui affichera mes résultats %>
    <div data-reset-target="list">
      <%# Si je trouve des restaurants dans les résultats de ma recherche %>
      <% @users.each do |user| %>
        <% friends = [] %>
        <% @friendships.each do |friendship| %>
          <% if (current_user == User.find(friendship.user_id)) %>
            <% friends.insert(-1, friendship.friend_id) %>
          <% end %>
        <% end %>
        <% unless (user == current_user || friends.include?(user.id)) %>
          <% if friends.any? %>
              <%= user.username %>
              <%= link_to "Add", friendships_path(user), data: {turbo_method: :post, turbo_confirm: "Are you sure?"}, class: "btn btn-success" %>
          <%# Sinon %>
          <% else %>
            <%# On affiche le message suivant %>
            <p>Sorry, no friends found.</p>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

<div class="container m-3">
  <h1 class="mb-3">Pending requests</h1>
  <% @friendships.each do |friendship| %>
    <% if (current_user == User.find(friendship.user_id) && friendship.status == "pending") %>
      <p>Your request for <%=  User.find(friendship.friend_id).username %> is pending</p>
    <% end %>
  <% end %>
</div>

<div class="container m-3">
  <h1>Friends requests</h1>
  <ul>
    <% @friendships.each do |friendship| %>
      <% if (current_user == User.find(friendship.friend_id) && friendship.status == "pending") %>
        <li  class="list-unstyled">
          <p>Friend request for
          <%  if (User.find(friendship.user_id).avatar.attached?) %>
            <%= link_to friendship_path(friendship) do %>
              <%= cl_image_tag User.find(friendship.user_id).avatar.key, class: "avatar", alt: "avatar" %>
            <% end %>
          <% else %>
            <%= link_to friendship_path(friendship) do %>
              <%= image_tag "https://png.pngtree.com/png-vector/20221018/ourmid/pngtree-master-chef-logo-illustration-png-image_6351381.png", class: "avatar", alt: "avatar" %>
            <% end %>
          <% end %>
          <%= User.find(friendship.user_id).username %></p>
          <p><%= link_to "Accept", accept_path(friendship), class: "btn btn-success m-1", data: { turbo_method: "PATCH" } %><%= link_to "Decline", decline_path(friendship), class: "btn btn-danger m-1", data: { turbo_method: "PATCH" } %></p>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

<div class="container m-3">
  <h1>My Friends</h1>
  <ul>
    <% @friendships.each do |friendship| %>
    <% if ((current_user == User.find(friendship.user_id) || current_user == User.find(friendship.friend_id)) && friendship.status == "accepted") %>
      <li class="list-unstyled">
        <%  if (User.find(friendship.user_id).avatar.attached?) %>
          <%= link_to friendship_path(friendship) do %>
            <%= cl_image_tag User.find(friendship.user_id).avatar.key, class: "avatar", alt: "avatar" %>
          <% end %>
        <% else %>
          <%= link_to friendship_path(friendship) do %>
            <%= image_tag "https://png.pngtree.com/png-vector/20221018/ourmid/pngtree-master-chef-logo-illustration-png-image_6351381.png", class: "avatar", alt: "avatar" %>
          <% end %>
        <% end %>
        <%= link_to "#{ User.find(friendship.user_id).username }", friendship_path(friendship), class: "text-decoration-none" %>
        <%= link_to friendship_path(friendship), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "text-black" do %>
          <i class="fa-solid fa-trash-can"></i>
        <% end %>
      </li>
    <% end %>
  </ul>
  <% end %>
</div>

<div>
-->

app/views/friendships/show.html.erb
<!--
<h1 class="m-3 text-center"><%= @user.username %></h1>


<div class="d-flex justify-content-center align-items-center">
  <%  if (@user.avatar.attached?) %>
    <img src="<% cl_image_path @user.avatar.key %>" class="avatar-large img-fluid rounded-start" alt="avatar">
  <% else %>
    <img src="https://png.pngtree.com/png-vector/20221018/ourmid/pngtree-master-chef-logo-illustration-png-image_6351381.png" class="avatar-large img-fluid rounded-start" alt="avatar">
  <% end %>
</div>

<div data-controller="showcat">
  <div class="d-flex justify-content-between align-items-center m-3">
    <button class="btn btn-ghost" data-action="focus->showcat#toggle" >All</button>
    <button class="btn btn-ghost" data-action="focus->showcat#toggle">Collections</button>
    <button class="btn btn-ghost">Reviews/Photos</button>
  </div>

  <div data-showcat-target="all">
    <%= render "components/favorite_cards", collection: @collection %>
  </div>

  <div class="d-none" data-showcat-target="collections">
    <% @collections.each do |collection| %>
      <p><%= collection.name %></p>
    <% end %>
  </div>
</div>
-->

<div class="main-content">

  <!-- Header avec photo, nom et username -->
  <div class="profil-header">
    <div class="profil-header-image">
      <% if (@user.avatar_color.present?) %>
        <div class="user-avatar" style="width: 80px; height: 80px; background-color: <%= @user.avatar_color %>;">
          <%= @user.first_name[0] %><%= @user.last_name[0] %>
        </div>
      <% else %>
        <img src="https://png.pngtree.com/png-vector/20221018/ourmid/pngtree-master-chef-logo-illustration-png-image_6351381.png" class="avatar-large img-fluid rounded-start" alt="avatar">
      <% end %>
    </div>
    <div class="profil-header-info">
      <div class="profil-name">
        <h2><%= @user.first_name %> <%= @user.last_name %></h2>
        <p>@<%= @user.username %></p>
      </div>
    </div>
  </div>

  <!-- Data sur le profil -->
  <div class="profil-data">
    <div class="profil-data-item">
      <p class="profil-data-number"><%= @user.collections.count %></p>
      <p class="profil-data-text">collections</p>
    </div>
    <div class="profil-data-item">
      <p class="profil-data-number"><%= @user.saved_restaurants.count %></p>
      <p class="profil-data-text">restaurants</p>
    </div>
    <div class="profil-data-item">
      <p class="profil-data-number"><%= Friendship.where(status: 1).where(user: @user).or(Friendship.where(status: 1).where(friend: @user)).count %></p>
      <p class="profil-data-text">friends</p>
    </div>
  </div>

  <div data-controller="showcat" class="profil-menu">
    <div class="profil-menu-btn">
      <%= link_to "Collections", switch_tab_path("collections"), data: { turbo_method: :post }, id: "collections-tab-button", class: "tab-active" %>
      <%= link_to "Photos", switch_tab_path("photos"), data: { turbo_method: :post }, id: "photos-tab-button" %>
      <%= link_to "Comments", switch_tab_path("reviews"), data: { turbo_method: :post }, id: "reviews-tab-button" %>
    </div>

    <div id="profil-content" class="profil-content" data-showcat-target="collections">
      <div class="collection-cards">
        <%= render partial: "components/collection_card", collection: @collections, as: :collection %>
      </div>
    </div>
  </div>

</div>