config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :restaurants, only: :show do
    # resources :reviews, only: [:create]
    resources :saved_restaurants, only: [:create]
    # resources :collections, only: [:new, :create, :index]
    resources :collections, only: [:index]
  end

  resources :saved_restaurants, only: [:update] do
    resources :reviews, only: [:create]
  end
  resources :reviews, only: [:destroy]

  resources :restaurants do
    patch "update_collection", to: "restaurants#update_collection", as: :collection
  end

  # get "/restaurants/:id", to: "restaurants#show", as: "restaurant"

  # À VÉRIFIER
  resources :collections, only: [:new, :create, :index, :show, :destroy]

  resources :friendships, except: %i[edit update new]
  get "friendships", to: "friendship#new"

  patch "friendships/:id/accept", to: "friendships#accept", as: :accept
  patch "friendships/:id/decline", to: "friendships#decline", as: :decline

  get "dashboard", to: "pages#dashboard"
  post 'dashboard/switch-window/:tab_name', to: "pages#switch_window", as: :switch_tab
  get "feed", to: "pages#feed"
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_name,
  against: :name,
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many :saved_restaurants, dependent: :destroy
  has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :reviews, dependent: :destroy
  has_many :collections, dependent: :destroy
  has_many :saved_restaurants, dependent: :destroy
  has_many :restaurants, through: :saved_restaurants

  def friends
    all_accepted_friendships = Friendship.where(status: 1).where(user: self).or(Friendship.where(status: 1).where(friend: self))
    # Sortir les id de ceux-là
    ids = all_accepted_friendships.map do |friendship|
      if friendship.user == self
        friendship.friend.id
      else
        friendship.user.id
      end
    end
    return User.where(id: ids)
  end

  def friends_restaurants
    friends = self.friends.pluck(:id)
    restaurant_ids = SavedRestaurant.where(user_id: friends).pluck(:restaurant_id)
    Restaurant.where(id: restaurant_ids)
  end
end

app/controllers/restaurants_controller.rb
require "open-uri"

class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  # GET /ezhfuhef/:restaurant_id
  def set_restaurant
    # call api en utilisant l'restaurant_id pour récupérer les informations du restaurant
    # Avec ces informations je fabrique mon instance SI elle n'existe pas deja
    # restaurant = Restaurant.find_or_create(datas de la reponse api)
    # je redirect_to vers la restaurant_path(restaurant)
  end

  def show
    @user = current_user
    # trouver les relations entre nous et qqun d'autre qui ont le statut accepté
    @friends = current_user.friends

    if Restaurant.find_by(id: params[:id])
      @restaurant = Restaurant.find(params[:id])
    else
      restaurant_data = GetGooglePlaceDetailsService.new(params[:id]).call
      restaurant_params = { name: restaurant_data.dig("displayName", "text"), address: restaurant_data.dig("formattedAddress"), category: restaurant_data.dig("primaryTypeDisplayName", "text"), rating: restaurant_data.dig("rating"), phone_number: restaurant_data.dig("nationalPhoneNumber"), website: restaurant_data.dig("websiteUri") }
      @restaurant = Restaurant.find_by(restaurant_params)

      if @restaurant.nil?
        @restaurant = Restaurant.create(restaurant_params)
        @photos = restaurant_data["photos"].map do |photo_data|
          img_uri = GetGooglePhotosDataService.new(photo_data["name"]).call
          photo_file = URI.parse(img_uri).open
          @restaurant.images.attach(io: photo_file, filename: "#{img_uri}.png", content_type: "image/png")
          @restaurant.save
        end
      end

      respond_to do |format|
        format.html # Rendu pour une page HTML
        format.json { render json: @restaurants } # Permet aussi d'utiliser en API
      end
    end

    @images = @restaurant.images
    # @image = @images.sample
    @collections = Collection.where(user_id: current_user.id)
    @saved_restaurant = SavedRestaurant.find_by(restaurant: @restaurant, user: current_user)
    @saved_restaurants = SavedRestaurant.where(user: current_user)
    @review = Review.new
    @reviews = Review.all
  end

  def update_collection
    @restaurant = Restaurant.find(params[:restaurant_id])
    @saved_restaurant = SavedRestaurant.find_or_create_by(restaurant: @restaurant, user: current_user)
    @collections = Collection.where(user: current_user)

    if params[:collection_ids]
      params[:collection_ids].each do |collec_id|
        SavedRestaurantsCollection.create(collection: Collection.find(collec_id), saved_restaurant: @saved_restaurant)
      end
    else
      @saved_restaurant.destroy
    end

    @saved_restaurant.saved_restaurants_collections.where.not(collection_id: params[:collection_ids]).destroy_all

    redirect_to collections_path, format: :html
  end

  def destroy
    @saved_restaurant = SavedRestaurant.find(params[:format])
    @photo = @saved_restaurant.photos.find(params[:id])
    @photo.destroy
    redirect_to restaurant_path(@saved_restaurant.restaurant)
  end
end

app/views/restaurants/show.html.erb
<%= render "components/image_carousel", restaurant: @restaurant %>

<div class="px-4 py-4">
  <div class="tagdiv">
    <p class="px-3 fs-6 fw-semibold text-white"><%= @restaurant.category.split.first %></p>
  </div>
</div>

<div class="px-4">
  <h1 class="title fs-6 fw-semibold"><%= @restaurant.name %></h1>
</div>
<%= render "components/restaurant_details" %>

<!-- Modal pour choisir la catégorie qui s'ouvre en mode pop-up -->
<div class="modal fade" id="collectionModal" tabindex="-1" aria-labelledby="collectionModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="collectionModalLabel">Choose a collection</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with url: restaurant_collection_path(@restaurant), method: :patch, local: true do |f| %>
          <div class="collection-cards-modal">
            <% @collections.each do |collection| %>
              <input type="checkbox" id="collection_<%= collection.id %>" name="collection_ids[]" value="<%= collection.id %>" class="input-none" <%= 'checked' if SavedRestaurantsCollection.where(saved_restaurant: @saved_restaurant, collection: collection).present? %>>
              <label for="collection_<%= collection.id %>" class="collection-card-modal">
                <span class="collection-emoji"><%= collection.emoji %></span>
                <span class="collection-name"><%= collection.name %></span>
              </label>
            <% end %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <%= f.submit "Save", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- ajouter une photo via cloudinary à notre saved restaurant-->
<%#= simple_form_for(@saved_restaurant) do |f| %>
  <!-- [...] -->
  <%#= f.input :photos, as: :file, input_html: { multiple: true } %>
  <!-- [...] -->
  <%#= f.button :submit %>
<%# end %>

  <!-- afficher les photos cloudinary du saved restaurant -->
<%# @saved_restaurant.photos.each do |photo| %>
  <%#= cl_image_tag(photo.key, width: 300, height: 200, crop: "scale", effect: "cartoonify")  %>
<%# end %>


<% @saved_restaurants.each do |saved_restaurant| %>
  <% if (saved_restaurant.restaurant == @restaurant) %>

    <%= render "components/img_upload_carousel", saved_restaurant: @saved_restaurant %>

    <div class="container px-4">
      <h1 class="fw-semibold fs-5 mt-3 mb-3">Add my photos</h1>
      <div class="row">
        <div class="col-xs-12 d-flex justify-content-between">
          <%= simple_form_for @saved_restaurant do |f| %>
            <div class="d-flex justify-content-between">
              <%= f.input :photos, input_html: { multiple: true, class: "form-upload w-75" }, label: false %>
              <%= button_tag type: "submit", class: "btn-photo" do %>
                <i class="fa-solid fa-plus"></i>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>


<div class="container px-4">
  <% if (!@saved_restaurant.nil? && @saved_restaurant.restaurant == @restaurant) %>
    <h1 class="fw-semibold fs-5 mt-3 mb-2">Reviews</h1>
    <div class="row mb-3">
      <div class="col-xs-4">
        <%= simple_form_for([@saved_restaurant, @review], data: { controller: "submit" }) do |f| %>
          <%= f.input :content, input_html: { class: "form-content" }, label: false %>
          <div class="d-flex justify-content-between align-items-center">
            <%= f.input :user_rating, collection: (1..5).to_a, label: false, input_html: {data: { controller: "star-rating", action: "click->form-submit#submit"}, class: "no-marg"}  %>
            <%= button_tag type: "submit", class: "btn-photo" do %>
              <i class="fa-solid fa-plus"></i>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <% @reviews.each do |review| %>
      <% if (review.saved_restaurant.restaurant == @restaurant && (review.user == current_user || @friends.include?(review.user))) %>
      <div class="my-3 py-3 border-review">
        <p class="mb-2">
          <span class="fw-semibold"><%= review.user.username %></span>
          <%= review.content %>
        </p>
        <div class="d-flex justify-content-between align-items-center">
          <div class="restaurant-card-rating">
            <% full_stars = review.user_rating.floor %>
            <% empty_stars = 5 - full_stars %>
            <% full_stars.times do %>
              <%= image_tag "star-fill.svg", width: 20, height: 20 %>
            <% end %>
            <% empty_stars.times do %>
              <%= image_tag "star.svg", width: 20, height: 20 %>
            <% end %>
          </div>
          <% if (review.user == current_user) %>
            <%= link_to review_path(review), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "text-black" do %>
              <i class="fa-solid fa-trash-can btn-photo d-flex align-items-center justify-content-center"></i>
            <% end %>
          <% end %>
        </div>
      </div>
      <% end %>
    <% end %>
  <% end %>
</div>